services:
  postgres:
    image: postgres:18.3-alpine3.23
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_SCHEMA}
    ports:
      - ${DATABASE_PORT}:5432
  mailpit:
    image: axllent/mailpit:v1.3.4
    ports:
      - 8025:8025
      - 1025:1025
